name: Build & Deploy
on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy app
        uses: appleboy/ssh-action@v0.1.2
        with:
          host: ${{secrets.SSH_HOST}} # IP address of the server you wish to ssh into
          key: ${{secrets.SSH_KEY}} # Private key of the server
          username: ${{ secrets.SSH_USERNAME }} # User of the server you want to ssh into

          script: |
            cd /
            rm -rf /var/www/hifi/
            rm -rf /home/cloned-repo-hifi/
            cd /var/www
            mkdir hifi
            cd /home
            mkdir cloned-repo-hifi
            cd cloned-repo-hifi
            git clone https://github.com/Andrii-Yukhymenko/hifi-agency-landing-page.git
            cd hifi-agency-landing-page/
            cp -r app/* /var/www/hifi
